# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/workdir
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test
      - run: yarn run cov:send

  "node-latest":
    docker:
      - image: circleci/node:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test

  "docker":
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - run: npm run docker

workflows:
  version: 2
  build:
    jobs:
      - "node-8"
      - "node-latest"
      - "docker"