version: 2.1

orbs:
  codacy: codacy/base@0.3.3

jobs:
  build_and_test:
    parameters:
      node_version:
        type: string
        default: latest
        description: Specify the node version
    docker:
      - image: circleci/node:<<parameters.node_version>>
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Test
          command: yarn run test

  publish_local:
    machine: true
    working_directory: ~/workdir
    steps:
    - attach_workspace:
        at: ~/
    - run:
        name: Publish local docker
        command: docker build --no-cache --tag codacy/codacy-remark-lint:dev .
    - run:
        name: Save docker to file
        command: |
          mkdir workspace
          docker save --output workspace/codacy-remark-lint.tar codacy/$CIRCLE_PROJECT_REPONAME:dev
    - persist_to_workspace:
        root: workspace
        paths:
        - codacy-remark-lint.tar

  plugins_test:
    machine: true
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/codacy-remark-lint.tar
      - run: 
          name: Clone test project
          working_directory: ~/
          command: |
            (git -C ~/codacy-plugins-test fetch --all && 
              git -C ~/codacy-plugins-test reset --hard origin/master) || 
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - restore_cache:
          key: dependencies-{{ checksum "~/codacy-plugins-test/build.sbt" }}
      - run: 
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - save_cache:
          key: dependencies-{{ checksum "~/codacy-plugins-test/build.sbt" }}
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
      - run:
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt "runMain codacy.plugins.DockerTest json codacy/$CIRCLE_PROJECT_REPONAME:dev"
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest pattern codacy/$CIRCLE_PROJECT_REPONAME:dev"

  publish:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load docker from file
          command: docker load --input ~/codacy-remark-lint.tar
      - run:
          name: Docker tag
          command: |
            docker tag codacy/$CIRCLE_PROJECT_REPONAME:dev codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag codacy/$CIRCLE_PROJECT_REPONAME:dev codacy/$CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Docker login
          command: npm run docker:login
      - run:
          name: Docker push
          command: |
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest


workflows:
  version: 2
  build:
    jobs:
      - codacy/checkout_and_version
      - build_and_test:
          name: build_and_test_8
          node_version: "8"
          requires:
            - codacy/checkout_and_version
      - build_and_test:
          name: build_and_test_latest
          node_version: latest
          requires:
            - codacy/checkout_and_version
      - publish_local:
          requires:
            - codacy/checkout_and_version
      - plugins_test:
          requires:
            - publish_local
      - publish:
          context: CodacyDocker
          requires:
            - build_and_test_8
            - build_and_test_latest
            - plugins_test
          filters:
            branches:
              only:
              - master
      - codacy/tag_version:
          filters:
            branches:
              only:
              - master
          context: CodacyAWS
          requires:
            - publish